### ISSUE TITLE
Ubuntu requirements to run NToolbox.exe

### ISSUE THREAD

**Issue by febs** [Jsl-1/NFirmwareEditor#1]
Hello, just dropping in to suggest that the README.md for this project should contain the instructions for running on Linux. Especially, I had to install the "mono-complete" on Ubuntu 16.04 (Xenial) here otherwise I would get this error:

Unhandled Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.

**Comment by Jsl-1** [comment]
@febs 

Hi, 
I agree and i will  ;)

**Comment by febs** [comment]
Thank you, your work is outstanding and giving this project an incredible boost! If you have a paypal account I'd happily tip you a coffee. :-)

**Comment by Jsl-1** [comment]
README file updated on linux branch ;) and a new build is available to download ;)

**Comment by febs** [comment]
This still shows Windows only though :-)

![image](https://cloud.githubusercontent.com/assets/604435/22298122/a9f02a1e-e31f-11e6-887a-b80620df808c.png)


I can't find the new release to download. Clicked on "releases", here:
https://github.com/Jsl-1/NFirmwareEditor/releases

and I could only see the latest release from October 2016. Why are you publishing them elsewere? Just curious. :-)

Thanks again

**Comment by febs** [comment]
Oh, of course, the Linux branch, it wasn't merged yet! :-) 
The paypal email address is the same though. I donated there already. Is that you?

**Comment by Jsl-1** [comment]
@febs 
I don't do this for money, and i have no paypal account enabled ;) The paypal address is not mine ;) 
Furthermore, it's not my code ;) 

Anyway, Thank you ;)
